version: "3"

dotenv: ['.env']

tasks:
  generate-go:
    aliases:
      - gen-go
    desc: "Generate golang code from proto files"
    # deps: [make-dir]
    cmds: 
      - $CMD $PROTOS_DIR/authentication.proto $GO_OUT/authentication $GO_OPT_GRPC_OUT/authentication $GRPC_OPT
      - $CMD $PROTOS_DIR/authorization.proto $GO_OUT/authorization $GO_OPT_GRPC_OUT/authorization $GRPC_OPT

  make-dir:
    cmds:
      - $SCRIPTS_DIR/prepare.sh
